export const catPortfolioData = {
  meta: {
    concept: "Cat Portfolio",
    ownerCredit: "Made with love by us",
    ownerSite: "https://yewon.cc",
    ownerSiteLabel: "yewon.cc",
    dedication: "This website is dedicated to my lovely cat.",
    servants: [
      {
        id: "main-servant",
        role: "Main Servant",
        label: "yewon.cc",
        href: "https://yewon.cc",
      },
      {
        id: "daddy-long-legs",
        role: "Daddy-Long-Legs",
        label: "parkdohyun.com",
        href: "https://www.parkdohyun.com/",
      },
    ],
  },
  profile: {
    name: "임자",
    tagline: "따뜻한 자리와 조용한 오후를 좋아하는 고양이",
    intro:
      "조용하지만 집 안 흐름은 다 꿰고 있어요. 따뜻한 자리는 항상 먼저 차지하고, 밥 시간은 절대 놓치지 않아요.",
    tags: ["#집사감시관", "#낮잠전문가", "#간식헌터", "#창밖관찰자", "#똥고양이", "#표독미", "#캣타워정복", "#츄르스틱"],
    heroImage: "/gallery/main_picture.png",
    heroImageAlt: "큰 눈으로 카메라를 바라보는 임자 프로필 사진",
    summaryCards: [
      { id: "age", label: "나이", value: "6개월", note: "2025.10.20 출생" },
      { id: "personality", label: "성격", value: "표독스러움", note: "눈빛으로 집사를 제압" },
      { id: "snack", label: "좋아하는 간식", value: "고기, 냥태깡, 츄르스틱", note: "간식 소리에는 즉시 반응" },
    ],
    details: [
      { id: "birth", label: "태어난 날", value: "2025.10.20", icon: "cake" },
      { id: "location", label: "사는 곳", value: "경기도 의왕시", icon: "home" },
      { id: "breed", label: "품종", value: "아메리카 숏헤어", icon: "badge" },
      { id: "gender", label: "성별", value: "공주", icon: "user" },
      { id: "nickname", label: "별명", value: "똥고양이", icon: "sparkles" },
      { id: "favoritePlace", label: "좋아하는 장소", value: "캣타워 맨 위, 의자 위", icon: "home" },
      { id: "hospital", label: "자주 다니는 병원", value: "청계동물종합병원", icon: "stethoscope" },
      { id: "ownerName", label: "주인 이름", value: "서예원", icon: "user" },
    ],
  },
  stats: [
    { id: "affection", label: "애교도", score: 99, note: "먼저 오지는 않지만 옆자리는 지켜요" },
    { id: "playful", label: "장난기", score: 100, note: "끈 장난감 한정 집중력이 급상승해요" },
    { id: "appetite", label: "식탐", score: 91, note: "간식 서랍 소리에 즉시 반응해요" },
    { id: "sleep", label: "잠자는 시간", score: 88, note: "하루 대부분 자는 중이에요" },
    { id: "zoomies", label: "우다다력", score: 100, note: "밤 8시 이후 짧고 강해요" },
    { id: "supervision", label: "집사 감시력", score: 94, note: "화장실, 부엌 동선까지 파악해요" },
  ],
  gallery: [
    {
      id: "imja-gallery-01",
      title: "햇살 아래",
      caption: "빛 반사되는 바닥에서 올려다보는 중.",
      src: "/gallery/picture11.jpg",
      alt: "햇살이 가득한 바닥에 앉아 올려다보는 임자",
    },
    {
      id: "imja-gallery-02",
      title: "거꾸로 낮잠",
      caption: "뒤집혀서 완전히 잠든 상태.",
      src: "/gallery/picture01.jpg",
      alt: "노란 패브릭 위에 거꾸로 누워 자는 임자",
    },
    {
      id: "imja-gallery-03",
      title: "퍼얼 목걸이",
      caption: "꽃 참 달린 퍼얼 목걸이 착용 중.",
      src: "/gallery/picture02.jpg",
      alt: "퍼얼 목걸이를 하고 창가에 앉은 임자",
    },
    {
      id: "imja-gallery-04",
      title: "배 보여주기",
      caption: "배 보여주기 허락한 날.",
      src: "/gallery/picture03.jpg",
      alt: "노란 이불 위에 뒤집혀 누운 임자",
    },
    {
      id: "imja-gallery-05",
      title: "터널 탐험",
      caption: "탈출할지 말지 고민 중.",
      src: "/gallery/picture04.jpg",
      alt: "캣 터널 안에서 카메라를 바라보는 임자",
      featured: true,
    },
    {
      id: "imja-gallery-06",
      title: "냉장고 점검",
      caption: "점검 나왔다가 걸림.",
      src: "/gallery/picture05.jpg",
      alt: "냉장고 안에 서 있는 임자",
    },
    {
      id: "imja-gallery-07",
      title: "책장 위 근무",
      caption: "위에서 내려다보는 자리가 좋아요.",
      src: "/gallery/picture06.jpg",
      alt: "책장 위에 누워 카메라를 내려다보는 임자",
    },
    {
      id: "imja-gallery-08",
      title: "초근접 눈 맞춤",
      caption: "렌즈 바로 앞까지 와서 응시.",
      src: "/gallery/picture07.jpg",
      alt: "카메라 가까이 얼굴을 들이민 임자",
    },
    {
      id: "imja-gallery-09",
      title: "책상 위 휴식",
      caption: "케이블 옆에서 쉬는 중.",
      src: "/gallery/picture08.jpg",
      alt: "나무 책상 위에서 쉬는 임자",
    },
    {
      id: "imja-gallery-10",
      title: "우다다 중",
      caption: "카메라도 따라가지 못한 속도.",
      src: "/gallery/picture09.jpg",
      alt: "빠르게 움직여 흔들린 임자",
    },
    {
      id: "imja-gallery-11",
      title: "완전 취침",
      caption: "발 들고 자는 중. 방해 금지.",
      src: "/gallery/picture10.jpg",
      alt: "이불 위에서 발을 들고 자는 임자",
    },
    {
      id: "imja-gallery-12",
      title: "대하품",
      caption: "카펫에서 대하품.",
      src: "/gallery/picture12.jpg",
      alt: "카펫 위에서 크게 하품하는 임자",
    },
    {
      id: "imja-gallery-13",
      title: "수달 아니고 고양이임",
      caption: "진짜예요.",
      src: "/gallery/picture13_otter.jpg",
      alt: "고양이임",
    },
  ],
  routine: [
    { time: "09:00", title: "집사 깨우기", description: "침대 주변을 한 바퀴 돌고 기다려요." },
    { time: "09:00", title: "아침밥 먹기", description: "그릇 앞에 앉아서 대기해요. 제일 정확한 시간이에요." },
    { time: "11:00", title: "창밖 구경", description: "새, 햇빛, 지나가는 사람 다 구경해요." },
    { time: "13:00", title: "낮잠", description: "거실이랑 방 오가면서 따뜻한 자리 탐색해요." },
    { time: "20:00", title: "우다다", description: "뛰고 멈추고는 아무 일도 없었다는 표정이에요." },
    { time: "24:00", title: "인간의 샤워구경", description: "문 앞에서 물소리 들으면서 대기해요." },
    { time: "01:00", title: "집사 옆에서 자기", description: "결국 옆에 와서 자요." },
  ],
  certifications: [
    {
      id: "combo",
      name: "혼합백신",
      catComment: "가방에 들어가면 병원인 거 이제 알아요.",
      records: [
        { round: "1회차", date: "2026.02.28" },
        { round: "2회차", date: "2026.03.20" },
        { round: "3회차", date: "2026.04.11" },
      ],
    },
    {
      id: "heartworm",
      name: "심장사상충",
      catComment: "또 가방.",
      records: [
        { round: "1회차", date: "2026.03.20" },
        { round: "2회차", date: "2026.04.20" },
      ],
    },
    {
      id: "rabies",
      name: "광견병 백신",
      catComment: "이번엔 왜인지 모르겠지만 맞았어요.",
      records: [
        { round: "1회차", date: "2026.04.11" },
      ],
    },
  ],
  memories: [
    {
      date: "2025.10.20",
      title: "임자가 태어난 날",
      description: "임자가 세상에 나온 날이에요.",
    },
    {
      date: "2026.02.25",
      title: "처음 집에 온 날",
      description: "낯선 공간에서 냄새 맡으면서 조심조심 다녔어요.",
    },
    {
      date: "2026.04.30",
      title: "포트폴리오가 생겼어요",
      description: "이렇게 멋진 포트폴리오가 생겼어요. 앞으로도 잘 부탁해요!",
    },
  ],
};
